version: "3.9"

services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "8081:80"          # 브라우저 접속: http://localhost:8081
    volumes:
      - ./app:/var/www/html
      - ./ops/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  php:
    build: ./ops/php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    environment:
      PHP_MEMORY_LIMIT: 256M

  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: herocomics
      MARIADB_USER: hero
      MARIADB_PASSWORD: heropass
    ports:
      - "33061:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./ops/db/init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro

volumes:
  dbdata:
