name: herocomics
services:

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - MARIADB_DATABASE=herocomics
      - MARIADB_USER_ADMIN=hc_admin
      - MARIADB_PASSWORD_ADMIN=adminpass
      - MARIADB_USER=hero
      - MARIADB_PASSWORD=heropass

    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    ports:
      - "127.0.0.1:33060:3306"   # 호스트 로컬로만 바인딩(충돌/외부노출 방지)
    volumes:
      - ../db:/var/lib/mysql
    #  - ./ops/initdb:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h 127.0.0.1 --silent || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s

  php:
    image: server-php:latest
    build:
      context: ./php82
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    env_file:
      - ./.env
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - MARIADB_DATABASE=herocomics
      - MARIADB_USER=hero
      - MARIADB_PASSWORD=heropass     # ← 여기서 확정
    volumes:
      - ../app:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    depends_on:
      - php
    ports:
      - "8888:80"
    volumes:
      - ../app:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/logs:/var/log/nginx

