services:
  mariadb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpass
      MARIADB_DATABASE: herocomics
      MARIADB_USER: hero
      MARIADB_PASSWORD: hero_pass
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -uroot -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 5s
      timeout: 3s
      retries: 20

  php:
    build:
      context: ./php74          # ← ./docker/php74 (X)
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ../app:/var/www/html    # ← ./app (X)

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - php
    ports:
      - "8081:80"
    volumes:
      - ../app:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # ← ./docker/nginx/... (X)

volumes:
  db_data:
