
services:
  nginx:
    image: nginx:1.27-alpine
    ports:
      - "8081:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - C:\herocomics\server\app\admin:/var/www/html/admin
    depends_on:
      - php

  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - ../app:/var/www/html

  mariadb:
    image: mariadb:10.11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: herocomics
      MARIADB_USER: hero
      MARIADB_PASSWORD: secret
    ports:
      - "33060:3306"
    volumes:
      - ./mariadb:/var/lib/mysql

