-- 임시 관리자 생성(SQL 덤프 복원 전 테스트 용도)
CREATE TABLE IF NOT EXISTS admins (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- 비밀번호: admin
INSERT IGNORE INTO admins (username, password)
VALUES ('admin', '$2y$10$R7y8i9CqD4X2G9Wm1Hc8xO1cE/3vZQfH7JZP6r2G8n2eD7R3zqSZe');
