
CREATE TABLE IF NOT EXISTS episode(
  id INT AUTO_INCREMENT PRIMARY KEY,
  comic_id INT NOT NULL,
  title VARCHAR(200) NOT NULL,
  no INT NOT NULL DEFAULT 1,
  is_published TINYINT NOT NULL DEFAULT 0,
  published_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_episode_comic FOREIGN KEY (comic_id) REFERENCES comic(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS page(
  id INT AUTO_INCREMENT PRIMARY KEY,
  episode_id INT NOT NULL,
  page_no INT NOT NULL,
  file_path VARCHAR(255) NOT NULL,    -- 예: uploads/episodes/123/0001.jpg
  width INT NULL,
  height INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_page_episode FOREIGN KEY (episode_id) REFERENCES episode(id) ON DELETE CASCADE,
  UNIQUE KEY uq_page_order (episode_id, page_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
